comment out debug lines in configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -147,20 +147,20 @@ export LDFLAGS="-L${INST_DIR}/lib -Wl,-rpath,${INST_DIR}/lib"
 
 export PKG_CONFIG_PATH="${INST_DIR}/lib/pkgconfig:$PKG_CONFIG_PATH"
 
-echo "=== OPENSSL_CFLAGS is ${OPENSSL_CFLAGS} ==="
-IncludeStripped=$(echo "${OPENSSL_CFLAGS}" | sed 's/^-I//g' | sed 's/ -I/ /g')
-echo "=== IncludeStripped is ${IncludeStripped} ==="
-ls "${IncludeStripped}"/* || true
-find "${IncludeStripped}" -type f | grep herr.h || true
+#echo "=== OPENSSL_CFLAGS is ${OPENSSL_CFLAGS} ==="
+#IncludeStripped=$(echo "${OPENSSL_CFLAGS}" | sed 's/^-I//g' | sed 's/ -I/ /g')
+#echo "=== IncludeStripped is ${IncludeStripped} ==="
+#ls "${IncludeStripped}"/* || true
+#find "${IncludeStripped}" -type f | grep herr.h || true
 # print herr.h if it exists
-if find "${IncludeStripped}" -type f -name "herr.h" | grep -q "herr.h"; then
-  echo "herr.h found in ${IncludeStripped}"
-  file=$(find "${IncludeStripped}" -type f -name "herr.h" | head -n 1)
-  echo "Using herr.h from ${file}"
-  cat "${file}" | head -n 10
-else
-  echo "herr.h not found in ${IncludeStripped}, this is expected if you are using OpenSSL"
-fi
+#if find "${IncludeStripped}" -type f -name "herr.h" | grep -q "herr.h"; then
+#  echo "herr.h found in ${IncludeStripped}"
+#  file=$(find "${IncludeStripped}" -type f -name "herr.h" | head -n 1)
+#  echo "Using herr.h from ${file}"
+#  cat "${file}" | head -n 10
+#else
+#  echo "herr.h not found in ${IncludeStripped}, this is expected if you are using OpenSSL"
+#fi
 
 # Configure libhv with dependency paths
 
